import { Component, OnInit, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
@Component({standalone:true,imports:[FormsModule,RouterLink,DatePipe],template:`<div class="container py-5"><div class="d-flex justify-content-between align-items-end mb-4"><div><p class="text-primary fw-semibold mb-1">Hola, {{api.user()?.name}}</p><h1 class="h2 mb-0">Tu panel</h1></div></div>
@if(api.role()==='student'){<div class="card shadow-sm p-4 mb-4"><h2 class="h5">Unirme a un curso</h2><div class="input-group"><input class="form-control" [(ngModel)]="code" placeholder="Código recibido de tu tutor/a"><button class="btn btn-primary" (click)="join()">Unirme</button></div>@if(msg()){<p class="small mt-2 mb-0">{{msg()}}</p>}</div>}
<div class="row g-4">@for(course of api.courses();track course.id){<div class="col-md-6 col-xl-4"><article class="card shadow-sm h-100 p-4"><span class="badge text-bg-light align-self-start">{{course.academic_year}} · {{course.level}}º</span><h2 class="h4 mt-3">{{course.name}}</h2><p class="text-secondary">{{course.tutor?.name || 'Tutoría pendiente'}}</p>@if(api.role()==='student'){<a class="btn btn-primary mt-auto" [routerLink]="['/cuestionario',course.id]">Completar cuestionario</a>}@else{<a class="btn btn-primary mt-auto" [routerLink]="['/resultados',course.id]">Analizar resultados</a>}</article></div>}@empty{<div class="col-12"><div class="alert alert-info">Todavía no tienes cursos asignados.</div></div>}</div>
@if(api.role()==='student' && api.attempts().length){<h2 class="h4 mt-5">Mis intentos anteriores</h2><div class="list-group shadow-sm">@for(a of api.attempts();track a.id){<div class="list-group-item p-3"><div class="d-flex justify-content-between"><strong>{{a.course.name}}</strong><span>{{a.created_at|date:'dd/MM/yyyy HH:mm'}}</span></div><div class="small text-secondary mt-2">@for(r of a.results;track r.aspect_id){<span class="badge text-bg-light me-2">{{r.aspect}}: {{r.average}}</span>}</div></div>}</div>}</div>`})
export class DashboardComponent implements OnInit {api=inject(ApiService);code='';msg=signal('');ngOnInit(){this.api.loadMe().subscribe();if(this.api.role()==='student')this.api.loadAttempts().subscribe()}join(){this.api.join(this.code).subscribe({next:()=>{this.msg.set('Te has unido correctamente.');this.code=''},error:e=>this.msg.set(e.error?.error||'Código no válido')})}}

